# Generated by Django 3.1 on 2020-08-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
